### ISSUE TITLE
Can i use this along side viper4android?

### ISSUE THREAD

**Issue by DRA7** [Magisk-Modules-Alt-Repo/audio-samplerate-changer#2]
I wanna use this cause i see sometimes the music cuts or like stutter does this help?

**Comment by yzyhk904** [comment]
This module itself doesn't disable the effects framework (used by equalizers) unlike "Audio Misc. Settings". Try this module because it may help to lower the stutter by its I/O scheduler optimizations. Additionally, I recommend using ["Audio Jitter Silencer"](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer) that may help, too.

I think you may not need viper4android, though. This module includes a mastering level re-sampler and has lower jitter, i.e., too low distortion to need equalizers.

**Comment by DRA7** [comment]
Okay ty I'll remove v4a and try what you suggested ty

**Comment by yzyhk904** [comment]
I forget to mention that this module raises sample rates more than 192 kHz which is the upper limit to be handled by equalizers. If you need, see RAEDME and edit the ZIP file of this module to lower the sample rates.

**Comment by skupjoe** [comment]
Viper clarity is a must though. When the new version of V4A-RE comes out for AIDL devices please consider it thank you!

**Comment by skupjoe** [comment]
(Yeah I know it is just EQ but it sounds nice. Sometimes that's all that matters)

**Comment by yzyhk904** [comment]
I think V4A-RE tries to erase only distortions by system-wide re-sampling at AudioFlinger, jitter and intermodulation a little bit. I believe V4A-RE is useless under this and other modules of mine because no pre-echo, no post echo, very little intermodulation and very little jitter distortion.

**Comment by skupjoe** [comment]
OK thanks- sounds like I will have some choices to make then! Whether to go extreme jitterless or just maybe V4A-RE + `audio-jitter-silencer` (_that is supported, right?_) for a middle-ground approach.

Currently, I cannot flash either this mod or V4A due to my device being AIDL-only ... I can make a separate feature request for AIDL support for `audio-samplerate-changer` if you'd like or if ever thingk you'd get around to it. (_maybe for your future device?_)

**Comment by yzyhk904** [comment]
I'm investigating the Android audioserver supporting only AIDL, but not certain yet whether I can support it or not.

By the way, you could use `audio-jitter-silencer` and `resampling-for-cheapies` with V4A-RE.
